# Default configuration for GNTO framework

# Model configuration
model:
  # Node encoder settings
  node_encoder:
    hidden_dims: [256, 128]
    output_dim: 128
    dropout: 0.1
    activation: "relu"
    batch_norm: true

  # Structure encoder settings
  structure_encoder:
    hidden_dim: 128
    num_layers: 3
    num_edge_types: 10
    gnn_type: "gcn"  # gcn, gat
    heads: 4  # for GAT
    dropout: 0.1
    pooling: "mean"  # mean, max, sum, attention
    residual: true

  # Prediction heads settings
  heads:
    hidden_dims: [128, 64]
    dropout: 0.1
    uncertainty: false
    loss_weights: null
    adaptive_weighting: true

  # Tasks to train/evaluate
  tasks: ["cost", "latency", "ranking"]

# Training configuration
training:
  # Optimization
  learning_rate: 0.001
  weight_decay: 0.00001
  optimizer: "adam"
  scheduler: "cosine"

  # Training loop
  epochs: 100
  batch_size: 32
  eval_every: 5
  save_every: 10
  early_stopping_patience: 20

  # Regularization
  grad_clip: 1.0
  dropout: 0.1

  # Data splits
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Data configuration
data:
  # Paths
  data_dir: "data"
  train_file: null
  val_file: null
  test_file: null

  # Processing
  max_nodes_per_plan: 100
  max_plans_per_batch: 32
  normalize_features: true

  # Feature configuration
  continuous_features:
    - "rows"
    - "ndv"
    - "selectivity"
    - "io_cost"
    - "cpu_cost"
    - "parallel_degree"

  categorical_features:
    operator_type: 50
    join_type: 10
    index_type: 20
    storage_format: 15
    hint: 30

  structure_features:
    - "is_blocking"
    - "is_pipeline"
    - "is_probe"
    - "is_build"
    - "stage_id"

# Inference configuration
inference:
  # Service settings
  batch_size: 32
  enable_monitoring: true

  # Fallback thresholds
  fallback_threshold:
    uncertainty_threshold: 0.5
    cost_confidence_threshold: 0.8
    latency_confidence_threshold: 0.8
    min_plan_score: 0.1

  # Performance
  warmup_predictions: 10
  max_concurrent_requests: 100

# General settings
experiment_name: "lqo_experiment"
output_dir: "outputs"
log_level: "INFO"
seed: 42
device: "auto"  # auto, cpu, cuda

# Monitoring
use_wandb: false
wandb_project: "gnto"
use_tensorboard: true
