
model:
  enc_hidden: 128
  head_hidden: 128
  z_dim: 128

train:
  x_path: data/IMDB/train_X.npy    # <- put your pre-featurized arrays here
  y_ms_path: data/IMDB/train_y_ms.npy
  # extra_path: data/IMDB/train_extra.npy   # e.g., PG cost, env vector
valid:
  x_path: data/IMDB/valid_X.npy
  y_ms_path: data/IMDB/valid_y_ms.npy
  # extra_path: data/IMDB/valid_extra.npy
test:
  x_path: data/IMDB/test_X.npy
  y_ms_path: data/IMDB/test_y_ms.npy
  # extra_path: data/IMDB/test_extra.npy
  # k_per_query: 64   # if each query has 64 enumerated plans

train_cfg:
  batch_size: 512
  epochs: 10
  lr: 0.001
  weight_decay: 1.0e-5
  pairwise_weight: 0.0
  log_interval: 25

out:
  model_path: artifacts/flat_cost.pt
